/*
 * WARNING: This is a generated file
 *
 * Generated by jcon | Josue Teodoro Moreira | GPL3
 * More info: https://github.com/J0sueTM/jcon
 */

#include "simple.h"
#include <string.h>

char *jcon_jcon_example_simple_1_to_json
(
  jcon_example_simple_1 *_obj
)
{
  char *out_json = malloc(6000 * sizeof(char));
  int json_i = 0;

  sprintf(out_json + json_i, "{");
  json_i += 1;

  sprintf(out_json + json_i, "\"j_int\": ");
  json_i += 8;
  sprintf(out + json_i, "%d", _obj->j_int);
  json_i += (int)((_obj->j_int) / 10);
  strcpy(out_json + json_i, ",\n");

  json_i += 2

  sprintf(out_json + json_i, "\"j_float\": ");
  json_i += 10;
  strcpy(out_json + json_i, ",\n");

  json_i += 2

  sprintf(out_json + json_i, "\"j_double\": ");
  json_i += 11;
  strcpy(out_json + json_i, ",\n");

  json_i += 2

  sprintf(out_json + json_i, "}");
  json_i += 1;

  return out_json;
}

char *jcon_jcon_example_simple_2_to_json
(
  jcon_example_simple_2 *_obj
)
{
  char *out_json = malloc(6000 * sizeof(char));
  int json_i = 0;

  sprintf(out_json + json_i, "{");
  json_i += 1;

  sprintf(out_json + json_i, "\"j_str\": ");
  json_i += 8;
  strcpy(out_json + json_i, ",\n");

  json_i += 2

  sprintf(out_json + json_i, "\"j_bool\": ");
  json_i += 9;
  strcpy(out_json + json_i, ",\n");

  json_i += 2

  sprintf(out_json + json_i, "\"j_arr\": ");
  json_i += 8;
  sprintf(out_json + json_i, "[");
  json_i += 1;

  sprintf(out_json + json_i, "]");
  json_i += 1;
  sprintf(out_json + json_i, ",\n");
  json_i += 2

  sprintf(out_json + json_i, "}");
  json_i += 1;

  return out_json;
}
