/*
 * file: src/generator.c
 * author: Josue Teodoro Moreira <teodoro.josue@protonmail.ch>
 * date: 07 September 2022
 *
 * Copyright (C) 2022 Josue Teodoro Moreira
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include "generator.h"

jcon_generator *jcon_generate_files
(
  jcon_parser *_parser,
  char        *_file,
  char        *_folder
)
{
  jcon_generator *gen = malloc(sizeof(jcon_generator));
  if (!gen)
    return NULL;

  gen->in_f = _file;
  gen->parser = _parser;
  int folder_len = strlen(_folder);
  if (_folder[folder_len - 1] == '/')
    _folder[folder_len - 1] = '\0';

  char *in_fbase = basename(_file);
  int in_fbase_len = strlen(in_fbase);
  in_fbase[in_fbase_len - 2] = '\0';
  gen->in_fbase = in_fbase;

  char out_fname[258];
  sprintf(out_fname, "%s/%s_jcon_gen.c", _folder, in_fbase);

  char msg[310];
  sprintf(msg, "Generating file %s", out_fname);
  jcon_log(JCON_INFO, msg);
  
  gen->out_f = fopen(out_fname, "w");
  if (!gen->out_f)
  {
    jcon_log(JCON_ERROR, "Could not open file to write");

    free(gen);
    return NULL;
  }

  jcon_generate_header(gen);
  jcon_generate_to_json(gen);

  fclose(gen->out_f);

  return gen;
}

void jcon_generate_header
(
  jcon_generator *_gen
)
{
  fprintf(_gen->out_f, "/*\n * WARNING: This is a generated file\n *\n");
  fprintf(_gen->out_f, " * Generated by jcon | Josue Teodoro Moreira | GPL3\n");
  fprintf(_gen->out_f, " * More info: https://github.com/J0sueTM/jcon\n");
  fprintf(_gen->out_f, " */\n\n");

  /* Programmer's job to include source files' folder on compiler args when compiling */
  fprintf(_gen->out_f, "#include \"%s.h\"\n#include <string.h>\n\n", _gen->in_fbase);
}

void jcon_generate_to_json
(
  jcon_generator *_gen
)
{
  jcon_parser *parser = _gen->parser;
  for (int i = 0; i < parser->obj_count; ++i)
  {
    fprintf(_gen->out_f, "char *jcon_%s_to_json\n(\n  %s *_obj\n)\n{\n", parser->objs[i].name, parser->objs[i].name);

    fprintf(_gen->out_f, "  char *out_json = malloc(6000 * sizeof(char));\n");
    fprintf(_gen->out_f, "  int json_i = 0;\n\n");
    int prop_i = 0;
    jcon_parser_obj *cur_obj = &parser->objs[i];
    for (int j = 0; j < cur_obj->token_count; ++j)
    {
      if (cur_obj->tokens[j] == JCON_TOKEN_PROP)
      {
        char *prop = cur_obj->props[prop_i];
        fprintf(_gen->out_f, "  sprintf(out_json + json_i, \"\\\"%s\\\": \");\n", prop);
        fprintf(_gen->out_f, "  json_i += %lu;\n", strlen(prop) + 3);
        ++prop_i;
      }
      else if (cur_obj->tokens[j] < JCON_TOKEN_INT)
      {
        char *tok_str = jcon_token_to_str(cur_obj->tokens[j]);
        fprintf(_gen->out_f, "  sprintf(out_json + json_i, \"%s\");\n", tok_str);
        fprintf(_gen->out_f, "  json_i += %lu;\n", strlen(tok_str));

        if (cur_obj->tokens[j] == JCON_TOKEN_ARR_END)
        {
          fprintf(_gen->out_f, "  sprintf(out_json + json_i, \",\\n\");\n");
          fprintf(_gen->out_f, "  json_i += 2\n\n");
        }
        else
          fprintf(_gen->out_f, "\n");
      }
      else
      {
        char *prop = cur_obj->props[prop_i - 1];
        switch (cur_obj->tokens[j])
        {
          case JCON_TOKEN_INT:
            fprintf(_gen->out_f, "  sprintf(out + json_i, \"%%d\", _obj->%s);\n", prop);
            /* TODO: Add to json_i ammount of decimals in _obj->prop */
            fprintf(_gen->out_f, "  json_i += (int)((_obj->%s) / 10);\n", prop);
            
            break;
          case JCON_TOKEN_FLOAT:
            break;
          case JCON_TOKEN_DOUBLE:
            break;
          case JCON_TOKEN_STR:
            break;
          case JCON_TOKEN_BOOL:
            break;
          default:
            break;
        }
        
        fprintf(_gen->out_f, "  strcpy(out_json + json_i, \",\\n\");\n\n");
        fprintf(_gen->out_f, "  json_i += 2\n\n");
      }
    }
    
    fprintf(_gen->out_f, "  return out_json;\n}\n");
    if (i < parser->obj_count - 1)
      fprintf(_gen->out_f, "\n");
  }
}
